"""added google_id, is_verified in user table

Revision ID: 631fef6b3b0a
Revises: 4892a6e15301
Create Date: 2025-11-22 01:51:15.004856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631fef6b3b0a'
down_revision: Union[str, Sequence[str], None] = '4892a6e15301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
